include "serialization.conf"

pekko {
  actor {
    provider = cluster

    allow-java-serialization = off
  }

  persistence {
    journal.plugin = "pekko.persistence.r2dbc.journal"
    snapshot-store.plugin = "pekko.persistence.r2dbc.snapshot"
    state.plugin = "pekko.persistence.r2dbc.state"
  }

  cluster {
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"

    sharding {
      number-of-shards = 100
    }
  }
}
