pekko.actor {
  serializers {
    jackson-cbor = "org.apache.pekko.serialization.jackson.JacksonCborSerializer"
  }
  serialization-bindings {
    "neon.infrastructure.serialization.CborSerializable" = jackson-cbor
  }
}

pekko.serialization.jackson {
  jackson-modules += "com.fasterxml.jackson.module.scala.DefaultScalaModule"
}
