import {
  ALL_TASK_STATES as DOMAIN_ALL_TASK_STATES,
  LEGAL_TRANSITIONS as DOMAIN_LEGAL_TRANSITIONS,
  STATE_LABEL as DOMAIN_STATE_LABEL,
  STATE_ORDER as DOMAIN_STATE_ORDER
  
  
  
  
  
} from "@neon/domain/task"
import { queryOptions } from "@tanstack/react-query"
import { apiClient } from "./client"
import type {PackagingLevel, Task, TaskPriority, TaskState, TaskTimelineEvent} from "@neon/domain/task";

export type { PackagingLevel, Task, TaskPriority, TaskState, TaskTimelineEvent }

// SKU and packaging metadata, keyed off skuId. The real backend joins these
// from the SKU aggregate; here it's a small lookup table that gives the
// drawer something descriptive to show.
const SKU_META: Record<string, { name: string; packaging: PackagingLevel }> = {
  s001: { name: "USB-C Cable 2m · Braided", packaging: "Each" },
  s002: { name: "Notebook A5 · Dotted", packaging: "Case" },
  s003: { name: "Ceramic Mug 12oz · White", packaging: "Inner" },
  s004: { name: "LED Desk Lamp · Black", packaging: "Pallet" },
  s005: { name: "Mechanical Keyboard · TKL", packaging: "Each" },
}

// Priority is derived from a small per-order map (mirrors the order's
// priority on the live API). Mock data here so the dashboard's at-risk
// logic and the drawer's priority dot agree.
const ORDER_PRIORITY: Record<string, TaskPriority> = {
  o001: "high",
  o004: "low",
  o005: "medium",
  o007: "high",
  o008: "low",
  o011: "medium",
  o012: "high",
  o013: "medium",
  o014: "medium",
  o015: "low",
  o017: "high",
  o018: "low",
  o019: "medium",
  o023: "high",
  o025: "low",
  o026: "medium",
}

// Happy-path states (no Cancelled) for stepper / timeline rendering. The
// happy path is what the wave / task aggregates linearly walk through.
const STATE_ORDER = DOMAIN_STATE_ORDER

// All five states. Used by the kanban (5 columns), filter options, and any
// caller that needs to reason about Cancelled as a terminal branch.
export const ALL_TASK_STATES = DOMAIN_ALL_TASK_STATES

// Centralized display label per state — kept here so toast text + tooltip
// text + filter labels never drift from each other.
export const STATE_LABEL = DOMAIN_STATE_LABEL

// Tailwind class map for the state's accent dot. Keeps the dot's color in
// the same place as the state's textual identity so both can be imported
// together. The bg-state-<slug> utilities are generated by @theme inline in
// app/styles.css.
export const STATE_DOT_CLASS: Record<TaskState, string> = {
  Allocated: "bg-state-allocated",
  Assigned: "bg-state-assigned",
  Cancelled: "bg-state-cancelled",
  Completed: "bg-state-completed",
  Planned: "bg-state-planned",
}

// Legal state transitions mirror the Scala typestate (Task.scala). The
// kanban's drag-to-transition + drawer's state-aware action set both read
// from this so the rules stay in one place.
export const LEGAL_TRANSITIONS = DOMAIN_LEGAL_TRANSITIONS

// Build the timeline retroactively from the task's createdAt + state.
// Each transition gets a synthetic delta from creation. Realistic but
// deterministic so the UI is stable across renders.
function buildTimeline(
  state: TaskState,
  createdAt: string,
  assignedTo: string | null
): Array<TaskTimelineEvent> {
  const start = new Date(createdAt).getTime()
  const min = (n: number) => new Date(start + n * 60 * 1000).toISOString()
  const events: Array<TaskTimelineEvent> = [
    { at: createdAt, by: "system", state: "Planned" },
  ]
  if (state === "Cancelled") {
    events.push({
      at: min(2),
      by: "system",
      note: "Auto-cancelled: source stock unavailable.",
      state: "Cancelled",
    })
    return events
  }
  if (state === "Allocated" || state === "Assigned" || state === "Completed") {
    events.push({ at: min(1), by: "system", state: "Allocated" })
  }
  if (state === "Assigned" || state === "Completed") {
    events.push({
      at: min(8),
      by: assignedTo ?? "system",
      state: "Assigned",
    })
  }
  if (state === "Completed") {
    events.push({
      at: min(22),
      by: assignedTo ?? "system",
      state: "Completed",
    })
  }
  return events
}

function enrich(task: Task): Task {
  const sku = SKU_META[task.skuId] ?? {
    name: `${task.skuId.toUpperCase()} · unspecified`,
    packaging: "Each" as const,
  }
  const priority: TaskPriority = ORDER_PRIORITY[task.orderId] ?? "medium"
  return {
    ...task,
    handlingUnitId: `hu_${task.id.replace(/^t/, "")}`,
    packagingLevel: sku.packaging,
    priority,
    skuName: sku.name,
    timeline: buildTimeline(task.state, task.createdAt, task.assignedTo),
  }
}

const MOCK_TASKS_BASE: Array<Task> = import.meta.env.DEV
  ? [
      {
        actualQuantity: null,
        assignedTo: null,
        createdAt: "2026-04-14T08:05:00Z",
        destinationLocationId: "l004",
        id: "t001",
        orderId: "o001",
        requestedQuantity: 5,
        skuId: "s001",
        sourceLocationId: "l001",
        state: "Allocated",
        taskType: "Pick",
        waveId: "w001",
      },
      {
        actualQuantity: null,
        assignedTo: "u003",
        createdAt: "2026-04-14T08:06:00Z",
        destinationLocationId: "l004",
        id: "t002",
        orderId: "o001",
        requestedQuantity: 2,
        skuId: "s003",
        sourceLocationId: "l002",
        state: "Assigned",
        taskType: "Pick",
        waveId: "w001",
      },
      {
        actualQuantity: 10,
        assignedTo: "u003",
        createdAt: "2026-04-14T07:35:00Z",
        destinationLocationId: "l005",
        id: "t003",
        orderId: "o004",
        requestedQuantity: 10,
        skuId: "s002",
        sourceLocationId: "l001",
        state: "Completed",
        taskType: "Pick",
        waveId: "w002",
      },
      {
        actualQuantity: null,
        assignedTo: null,
        createdAt: "2026-04-14T09:01:00Z",
        destinationLocationId: null,
        id: "t004",
        orderId: "o005",
        requestedQuantity: 3,
        skuId: "s001",
        sourceLocationId: null,
        state: "Planned",
        taskType: "Pick",
        waveId: "w003",
      },
      {
        actualQuantity: null,
        assignedTo: null,
        createdAt: "2026-04-14T09:10:00Z",
        destinationLocationId: "l001",
        id: "t005",
        orderId: "o001",
        requestedQuantity: 20,
        skuId: "s001",
        sourceLocationId: "l003",
        state: "Planned",
        taskType: "Replenish",
        waveId: null,
      },
      {
        actualQuantity: null,
        assignedTo: null,
        createdAt: "2026-04-13T14:05:00Z",
        destinationLocationId: null,
        id: "t006",
        orderId: "o007",
        requestedQuantity: 4,
        skuId: "s004",
        sourceLocationId: null,
        state: "Cancelled",
        taskType: "Pick",
        waveId: "w004",
      },
      {
        actualQuantity: 6,
        assignedTo: "u002",
        createdAt: "2026-04-14T06:50:00Z",
        destinationLocationId: "l005",
        id: "t007",
        orderId: "o013",
        requestedQuantity: 8,
        skuId: "s002",
        sourceLocationId: "l001",
        state: "Completed",
        taskType: "Pick",
        waveId: "w006",
      },
      {
        actualQuantity: 15,
        assignedTo: "u003",
        createdAt: "2026-04-13T16:35:00Z",
        destinationLocationId: "l004",
        id: "t008",
        orderId: "o014",
        requestedQuantity: 15,
        skuId: "s001",
        sourceLocationId: "l002",
        state: "Completed",
        taskType: "Pick",
        waveId: "w007",
      },
      {
        actualQuantity: 6,
        assignedTo: "u004",
        createdAt: "2026-04-13T16:40:00Z",
        destinationLocationId: "l005",
        id: "t009",
        orderId: "o015",
        requestedQuantity: 6,
        skuId: "s003",
        sourceLocationId: "l001",
        state: "Completed",
        taskType: "Pick",
        waveId: "w007",
      },
      {
        actualQuantity: null,
        assignedTo: "u002",
        createdAt: "2026-04-14T10:20:00Z",
        destinationLocationId: "l004",
        id: "t010",
        orderId: "o011",
        requestedQuantity: 4,
        skuId: "s005",
        sourceLocationId: "l002",
        state: "Assigned",
        taskType: "Pick",
        waveId: "w005",
      },
      {
        actualQuantity: null,
        assignedTo: null,
        createdAt: "2026-04-14T10:22:00Z",
        destinationLocationId: "l004",
        id: "t011",
        orderId: "o012",
        requestedQuantity: 7,
        skuId: "s001",
        sourceLocationId: "l001",
        state: "Allocated",
        taskType: "Pick",
        waveId: "w005",
      },
      {
        actualQuantity: 20,
        assignedTo: "u003",
        createdAt: "2026-04-13T11:25:00Z",
        destinationLocationId: "l001",
        id: "t012",
        orderId: "o018",
        requestedQuantity: 20,
        skuId: "s001",
        sourceLocationId: "l003",
        state: "Completed",
        taskType: "Putaway",
        waveId: "w009",
      },
      {
        actualQuantity: 12,
        assignedTo: "u004",
        createdAt: "2026-04-13T11:30:00Z",
        destinationLocationId: "l002",
        id: "t013",
        orderId: "o019",
        requestedQuantity: 12,
        skuId: "s002",
        sourceLocationId: "l003",
        state: "Completed",
        taskType: "Putaway",
        waveId: "w009",
      },
      {
        actualQuantity: null,
        assignedTo: "u002",
        createdAt: "2026-04-14T11:05:00Z",
        destinationLocationId: "l005",
        id: "t014",
        orderId: "o017",
        requestedQuantity: 3,
        skuId: "s004",
        sourceLocationId: "l001",
        state: "Assigned",
        taskType: "Pick",
        waveId: "w008",
      },
      {
        actualQuantity: null,
        assignedTo: null,
        createdAt: "2026-04-14T12:05:00Z",
        destinationLocationId: null,
        id: "t015",
        orderId: "o023",
        requestedQuantity: 9,
        skuId: "s003",
        sourceLocationId: null,
        state: "Planned",
        taskType: "Pick",
        waveId: "w010",
      },
      {
        actualQuantity: null,
        assignedTo: null,
        createdAt: "2026-04-14T09:30:00Z",
        destinationLocationId: "l002",
        id: "t016",
        orderId: "o001",
        requestedQuantity: 30,
        skuId: "s002",
        sourceLocationId: "l003",
        state: "Allocated",
        taskType: "Replenish",
        waveId: null,
      },
      {
        actualQuantity: 5,
        assignedTo: "u003",
        createdAt: "2026-04-13T09:05:00Z",
        destinationLocationId: "l005",
        id: "t017",
        orderId: "o025",
        requestedQuantity: 5,
        skuId: "s005",
        sourceLocationId: "l001",
        state: "Completed",
        taskType: "Pick",
        waveId: "w011",
      },
      {
        actualQuantity: null,
        assignedTo: null,
        createdAt: "2026-04-14T13:35:00Z",
        destinationLocationId: "l001",
        id: "t018",
        orderId: "o026",
        requestedQuantity: 25,
        skuId: "s001",
        sourceLocationId: "l003",
        state: "Allocated",
        taskType: "Transfer",
        waveId: null,
      },
      {
        actualQuantity: 4,
        assignedTo: "u004",
        createdAt: "2026-04-13T14:10:00Z",
        destinationLocationId: null,
        id: "t019",
        orderId: "o008",
        requestedQuantity: 4,
        skuId: "s003",
        sourceLocationId: null,
        state: "Cancelled",
        taskType: "Pick",
        waveId: "w004",
      },
      {
        actualQuantity: 7,
        assignedTo: "u002",
        createdAt: "2026-04-14T07:00:00Z",
        destinationLocationId: "l002",
        id: "t020",
        orderId: "o013",
        requestedQuantity: 7,
        skuId: "s004",
        sourceLocationId: "l003",
        state: "Completed",
        taskType: "Putaway",
        waveId: "w006",
      },
    ]
  : []

const MOCK_TASKS: Array<Task> = MOCK_TASKS_BASE.map(enrich)

export const taskQueries = {
  all: () =>
    queryOptions({
      queryFn: async () => {
        const result = await apiClient.get<Array<Task>>("/api/tasks")
        return result.unwrapOr(MOCK_TASKS).map((t) => enrich(t))
      },
      queryKey: ["tasks"] as const,
    }),
  detail: (id: string) =>
    queryOptions({
      enabled: !!id,
      queryFn: async () => {
        const result = await apiClient.get<Task>(`/api/tasks/${id}`)
        const found = result.unwrapOr(
          MOCK_TASKS.find((t) => t.id === id) ?? null
        )
        return found ? enrich(found) : null
      },
      queryKey: ["tasks", id] as const,
    }),
}

export { STATE_ORDER as TASK_STATE_ORDER }
