pekko {
  remote.artery {
    canonical.hostname = "127.0.0.1"
    canonical.port = 25520
  }

  cluster {
    seed-nodes = ["pekko://neon-wes@127.0.0.1:25520"]
  }

  persistence.r2dbc {
    connection-factory = ${pekko.persistence.r2dbc.postgres}
    postgres {
      host = "localhost"
      host = ${?NEON_DB_HOST}
      port = 5432
      port = ${?NEON_DB_PORT}
      database = "neon_wes"
      database = ${?NEON_DB_NAME}
      user = "neon"
      user = ${?NEON_DB_USER}
      password = "neon"
      password = ${?NEON_DB_PASSWORD}
    }
  }
}

neon {
  http {
    host = "0.0.0.0"
    host = ${?NEON_HTTP_HOST}
    port = 8080
    port = ${?NEON_HTTP_PORT}
  }
}
