laika.title = "Part II: The Domain Model"
laika.navigationOrder = [
  ch03-common-foundation.md
  ch04-typestates.md
  ch05-events.md
  ch06-policies.md
  ch07-services.md
  ch08-repositories.md
  ch09-project-wave-release.md
]
