laika.title = "Part III: The Infrastructure"
laika.navigationOrder = [
  ch10-actor-model.md
  ch11-cluster-sharding.md
  ch12-cqrs-projections.md
  ch13-http-api.md
  ch14-testing.md
  ch15-project-warehouse-day.md
]
